#!/usr/bin/env bash
set -euo pipefail

# setup-gui-auth.sh
# Purpose: Generate a random auth token for the GUI and write it to .env.auth
# The token is used by the Vite auth middleware to protect the control panel.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GUI_DIR="$SCRIPT_DIR/../gui"
AUTH_FILE="$GUI_DIR/.env.auth"

if [[ -f "$AUTH_FILE" ]]; then
    echo "Auth file already exists: $AUTH_FILE"
    echo "Current token:"
    grep GUI_AUTH_TOKEN "$AUTH_FILE" | sed 's/GUI_AUTH_TOKEN=/  /'
    echo ""
    read -r -p "Regenerate token? (yes/no): " CONFIRM
    if [[ "$CONFIRM" != "yes" ]]; then
        echo "Keeping existing token."
        exit 0
    fi
fi

# Generate a 32-character random token
TOKEN=$(openssl rand -hex 16)

cat > "$AUTH_FILE" <<EOF
# OpenClaw GUI auth token (auto-generated by setup-gui-auth.sh)
# Set to empty string to disable authentication
GUI_AUTH_TOKEN=$TOKEN
EOF

chmod 600 "$AUTH_FILE"

echo "Auth token generated and saved to: $AUTH_FILE"
echo ""
echo "Token: $TOKEN"
echo ""
echo "Access the GUI via:"
echo "  http://[your-ipv6-addr]:3000/?token=$TOKEN"
echo ""
echo "Or visit http://[your-ipv6-addr]:3000/login and enter the token manually."
echo ""
echo "To apply, restart the GUI service:"
echo "  sudo systemctl restart openclaw-gui.service"
echo ""
echo "To disable auth, set GUI_AUTH_TOKEN= (empty) in $AUTH_FILE"
